openapi: 3.0.3
info:
  title: Payment Token Adapter API
  version: 0.0.1
  description: >
    API Specification for the Payment Token Adapter from the External Beneficiary Portal
    
    This API is to be implemented by the DFSP
  license:
    name: Apache License Version 2.0, January 2004
    url: http://www.apache.org/licenses/

paths:
  /tokens:
    post:
      tags:
        - Register Token
      summary: Register new Payment Token.
      description: Register new Payment Token for mapping with a Payee ID
      operationId: registerToken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payeeId:
                  type: string
                  example: '256781466410'
                payeeIdType:
                  $ref: 'common.yaml#/components/schemas/IdType'
                paymentToken:
                  type: string
                  example: CM2903E3E0WE
            examples:
              register-token:
                value:
                  payeeId: '256784666410'
                  payeeIdType: MSISDN
                  paymentToken: CM2903E3E0WE
      responses:
        '201':
          description: 'Successful storage of the Payment Token Mapping'





