openapi: 3.0.3
info:
  title: payment-token-adapter
  version: 1.0.0
  contact: {}
servers:
  - url: http://localhost
paths:
  /tokens:
    post:
      summary: register-token
      description: register-token
      operationId: registerToken
      parameters:
        - name: ''
          in: header
          schema:
            type: string
            example: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payeeId:
                  type: string
                  example: '256781666410'
                payeeIdType:
                  type: string
                  example: MSISDN
                paymentToken:
                  type: string
                  example: CM2903E3E0WE
            examples:
              register-token:
                value:
                  payeeId: '256781666410'
                  payeeIdType: MSISDN
                  paymentToken: CM2903E3E0WE
      responses:
        '200':
          description: ''
  /parties/ALIAS/CM2903E3E0WE:
    get:
      summary: getMapping
      description: getMapping
      operationId: getmapping
      responses:
        '200':
          description: ''
tags: []

